language: scala
scala: 2.12.8

env:
  matrix:
    - TRAVIS_JDK=adopt@1.11.0-3
    - TRAVIS_JDK=adopt@1.8.212-03

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use "$_" && java -Xmx32m -version

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.jabba/jdk
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.lightbend.play/play-socket-io*

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
